version: '3.8'
services:
  etcd-node-0:
    image: docker.arvancloud.ir/bitnami/etcd:3.4.15
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data-node-0:/bitnami/etcd
    networks:
      - etcd_network
    environment:
      - ETCD_LOGGER=zap
      - ETCD_ROOT_PASSWORD=2wsx@WSX
      - ETCD_NAME=etcd-node-0
      - ETCD_DATA_DIR=/bitnami/etcd/data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 1

  etcd-node-1:
    image: docker.arvancloud.ir/bitnami/etcd:3.4.15
    ports:
      - "2479:2379"
      - "2480:2380"
    volumes:
      - etcd-data-node-1:/bitnami/etcd
    networks:
      - etcd_network
    environment:
      - ETCD_LOGGER=zap
      - ETCD_ROOT_PASSWORD=2wsx@WSX
      - ETCD_NAME=etcd-node-1
      - ETCD_DATA_DIR=/bitnami/etcd/data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 2
            ##################################################################
  apisix:
    image: docker.arvancloud.ir/apache/apisix:3.11.0-debian
    configs:  
      - source: apisix_config
        target: /usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd-node-1
      - etcd-node-0
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - etcd_network


        #############################################################################################################
  apisix-dashboard:
    image: docker.arvancloud.ir/apache/apisix-dashboard:3.0.1-centos
    configs:  # Use Docker configs instead of bind mounts
      - source: dashboard_config
        target: /usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - etcd-node-1
      - etcd-node-0
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - etcd_network

        #################################################################################################################

volumes:
  etcd-data-node-0:
  etcd-data-node-1:

networks:
  etcd_network:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

configs:
  dashboard_config:
    file: ./dashboard_conf/conf.yaml
  apisix_config:
    file: ./apisix_conf/config.yaml

